host: 0.0.0.0
port: 9091

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "git.localhost"
      policy: one_factor
    - domain: "grafana.localhost"
      policy: one_factor

session:
  name: authelia_session
  secret: your_random_secret
  expiration: 3600
  domain: localhost

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
